bot_token = "TOKEN"

[[allowed_chats]]
id = "CHATID"
admins.type = "AllAdmins"
messages.new_user_template = """\
سلام {TAGUSER}
به گروه {CHATNAME} خوشآ‌مدید.
برای دسترسی به گروه، لطفا گزینه صحیح را انتخاب کنید."""
messages.admin_approve = "تایید توسط ادمین ✅"
messages.admin_only_error = "❌ این گزینه صرفا توسط ادمین های گروه قابل انتخاب است"
messages.user_doesnt_match_error = "❌ این پیام برای شما نیست"
messages.wrong_answer = "❌ جواب انتخابی شما اشتباه بود، شما از گروه بن میشوید"
messages.admin_approved_user = "✅ شما این کاربر را تایید کردید"
messages.correct_answer = "✅ جواب شما درست بود! حالا میتوانید در گروه چت کنید"
